[build]
  publish = "build/web"
  command = "flutter build web --web-renderer html --base-href=/"

[build.environment]
  FLUTTER_WEB = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
