// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4oPUkqScbFlFnQaszWEHxVS4ErEScCgc',
    appId: '1:222181744079:web:b92044fe44e63ba8f346ba',
    messagingSenderId: '222181744079',
    projectId: 'farm-management-system-fae8c',
    authDomain: 'farm-management-system-fae8c.firebaseapp.com',
    storageBucket: 'farm-management-system-fae8c.firebasestorage.app',
    measurementId: 'G-QJ6T37LHQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4oPUkqScbFlFnQaszWEHxVS4ErEScCgc',
    appId: '1:222181744079:android:PLACEHOLDER',
    messagingSenderId: '222181744079',
    projectId: 'farm-management-system-fae8c',
    storageBucket: 'farm-management-system-fae8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4oPUkqScbFlFnQaszWEHxVS4ErEScCgc',
    appId: '1:222181744079:ios:PLACEHOLDER',
    messagingSenderId: '222181744079',
    projectId: 'farm-management-system-fae8c',
    storageBucket: 'farm-management-system-fae8c.firebasestorage.app',
    iosBundleId: 'com.example.livestockFarmManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4oPUkqScbFlFnQaszWEHxVS4ErEScCgc',
    appId: '1:222181744079:macos:PLACEHOLDER',
    messagingSenderId: '222181744079',
    projectId: 'farm-management-system-fae8c',
    storageBucket: 'farm-management-system-fae8c.firebasestorage.app',
    iosBundleId: 'com.example.livestockFarmManagement',
  );
}
